# Generated by Django 4.2.23 on 2025-08-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Checked In', 'Checked In'), ('Checked Out', 'Checked Out'), ('No Show', 'No Show')], default='Pending', max_length=20),
        ),
    ]
