# Generated by Django 4.2.23 on 2025-08-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_mealtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtransaction',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snacks', 'Snacks')], default='Breakfast', max_length=50),
        ),
    ]
